### ISSUE TITLE
feature request - add type field to Account and TokenDetails objects

### ISSUE THREAD

**Issue by ronaltboum** [taboola/backstage-api-java-client#14]
Hi, 
Feautre request:
When invoking the getTokenDetails function,  a TokenDetails object is returned.  Will you consider adding an account type (for example NETWORK, GENEREAL etc) as a field ?

On the same subject:   
When performing an HTTP GET request to backstage/api/1.0/users/current/allowed-accounts  a type field (NETWORK, PARTNER etc) is included in each one of the accounts.
However when invoking the same api via the backstage client library using the function getUserAllowedAccounts ,  an Account object is returned which does not contain the type field.  Will you consider adding the type field to the Account object ?

Best regards, Ron

**Comment by vladimanaev** [comment]
Adding additional endpoint that can supply current user account details #16
