### ISSUE TITLE
Backstage builder.build() throws an error -> Retrofit dependency bug

### ISSUE THREAD

**Issue by elad-yosifon** [taboola/backstage-api-java-client#20]
`Exception in thread "main" java.lang.NoSuchMethodError: okhttp3.HttpUrl.get(Ljava/lang/String;)Lokhttp3/HttpUrl;
	at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:458)
	at com.taboola.backstage.internal.CommunicationFactory.<init>(CommunicationFactory.java:34)
	at com.taboola.backstage.Backstage$BackstageBuilder.build(Backstage.java:219)`

```java
public CommunicationFactory(CommunicationConfig communicationConfig, SerializationConfig serializationConfig) {
        this.objectMapper = SerializationMapperCreator.createObjectMapper(serializationConfig);
        Builder retrofitBuilder = this.createRetrofitBuilder(communicationConfig);
        this.authRetrofit = retrofitBuilder.baseUrl /* <---- calling this function with a String throws an Exception */(communicationConfig.getAuthenticationBaseUrl()).build();
        this.retrofit = retrofitBuilder.baseUrl(communicationConfig.getBackstageBaseUrl()).build();
    }
```

how to reproduce:
`Backstage.builder().build();` -> version 1.0.12

**Comment by elad-yosifon** [comment]
this bug is fixed on Retrofit v2.6.0
https://github.com/square/retrofit/blob/master/CHANGELOG.md#user-content-version-260-2019-06-05

**Comment by elad-yosifon** [comment]
does version 1.0.13 work for you?
I'm still getting errors for the retrofit and okhttp3 deps....   it's like it should have never passed the compilation step.. can't explain it.

Even if I wrap the strings with `HttpUrl.parse(String)` method:
```java
// com.taboola.backstage.internal.CommunicationFactory:35
this.authRetrofit = retrofitBuilder.baseUrl(HttpUrl.parse(communicationConfig.getAuthenticationBaseUrl())).build();
this.retrofit = retrofitBuilder.baseUrl(HttpUrl.parse(communicationConfig.getBackstageBaseUrl())).build();
```
it still breaks on some other place, reproducer:
```java
Backstage.builder().build().authenticationService().clientCredentials(clientId, clientSecret);
```

**Comment by vladimanaev** [comment]
@elad-yosifon please dump your dependency tree here (e.g. for maven 'mvn dependency:tree')
