### ISSUE TITLE
log4j2.properties conflict with my log4j2.xml 

### ISSUE THREAD

**Issue by qlxucn** [taboola/backstage-api-java-client#24]
Hi there, 

Seems your `log4j2.properties` file overrides my log4j2.xml file and my logging not working. Could you exclude it from the final Jar when it's released?

Thanks so much.

**Comment by vladimanaev** [comment]
Hi @qlxucn,

Best would be if you would override it in your project.
I will check if we can exclude it from future releases.

Vladi

**Comment by qlxucn** [comment]
hi @vladimanaev, any update on this issue?

**Comment by vladimanaev** [comment]
@qlxucn, we wont be excluding this from the supplied jar.
I suggest you overriding those properties in your project like it's being done in all places.

If you have specific challenges please describe them and we will try to help.
