### ISSUE TITLE
Field visible_impressions doesn't exist in TopCampaignContentRow

### ISSUE THREAD

**Issue by makcpop** [taboola/backstage-api-java-client#26]
Hi, folks,
I use SDK for getting a content report and face an issue.
When I execute REST request manually - I see the following response 
```
GET /backstage/api/1.0/taboola-demo-advertiser/reports/
top-campaign-content/dimensions/item_breakdown?
start_date=2015-03-30&end_date=2015-03-30

{
  ...
    {
      ....
      "content_provider_name": "xxx",
      "impressions": 11111,
      "visible_impressions": 222,
      "ctr": 000,
      ....
    }
  ...
}
```
As you can see, the response contains the 'visible_impressions' field.

I discover SDK classes and found that class TopCampaignContentRow contains _**impressions**_ field, but doesn't contain _**visibleImpressions**_.
It looks like the field was forgotten in the TopCampaignContentRow, isn't it?

**Comment by vladimanaev** [comment]
Hi @makcpop,

Thanks for raising this issue.
We might have such missing fields which takes us time to add to SDK. Usually when API get additional fields SDK is lagging behind a bit.

If you see more such fields please list them here and we will add them to SDK.

Vladi

**Comment by vladimanaev** [comment]
Will be part of #32
