### ISSUE TITLE
Typo in DynamicFieldDataType?

### ISSUE THREAD

**Issue by gdiazinpwrd** [taboola/backstage-api-java-client#33]
I found an exception that happens when parsing the response of backstage.reportsService().getCampaignSummaryReport(), the response contains a value being "DATE" but the enum does not have such a member name.

<img width="588" alt="image" src="https://user-images.githubusercontent.com/63310248/83314059-46bfad80-a1de-11ea-864f-5160e6779df7.png">

I'm using version 1.0.6

<img width="489" alt="image" src="https://user-images.githubusercontent.com/63310248/83314076-5939e700-a1de-11ea-8850-e1ab2cdb8d76.png">

There is one called DATA, could it be a typo?

**Comment by gdiazinpwrd** [comment]
By the way, it would be great to add the original cause to the exception thrown by the SDK, so devs get info about the real issue.

The error message I got: java.util.concurrent.ExecutionException: com.taboola.backstage.exceptions.BackstageAPIConnectivityException: Failed to perform API call, might be due to internet connectivity issues

The real cause of the error: Can not construct instance of com.taboola.backstage.model.dynamic.DynamicFieldDataType from String value ("DATE"): value not one of declared Enum instance names: [MONEY, STRING, PERCENT, TIMESTAMP, BOOLEAN, DATA, FLOAT, NUMERIC, URL]

**Comment by vladimanaev** [comment]
@gdiazinpwrd, thanks for raising this. Fix will be part of 1.0.17.
